apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: affiliate-bounty-board-backend-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - abb.brojonat.com
    - incentivizethis.com
    - www.incentivizethis.com
    secretName: affiliate-bounty-board-backend-tls
  rules:
  - host: "abb.brojonat.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: affiliate-bounty-board-backend
            port:
              number: 80
  - host: "incentivizethis.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: affiliate-bounty-board-backend
            port:
              number: 80
  - host: "www.incentivizethis.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: affiliate-bounty-board-backend
            port:
              number: 80